### ISSUE TITLE
プレビューカードが読み込まれない

### ISSUE THREAD

**Issue by mimikun** [mimikun/mastodon#838]
### 問題を再現するための手順

1. mstdn.mimikun.jp にアクセスする
2. 適当なアカウントでログインする

発生

### 期待される振る舞い

画像が表示される

### 実際の振る舞い

画像が表示されない

### 詳細説明

main追従してから発生。

CSPの問題であると思われる。
2023/03/19はなんともなかったが、2023/03/20の20:00頃？から発生。風呂に入っている間のできごとであった。

### 環境

Mastodon (https://github.com/mastodon/mastodon/commit/94cbd808b5b3e7999c7e77dc724b7e8c9dd2bdec まで追従)
Vivaldi 5.7.2921.63 (Stable channel) (64-bit)

**Comment by mimikun** [comment]
CSP周りでイライラしかしないのでrevertでの解決を図る。

セキュリティは利便性を下げる 🖕

**Comment by mimikun** [comment]
`git blame` したけど見つからない 😢

**Comment by mimikun** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/13450321/226335497-4cda46b4-8b26-4357-aba4-9017d3f4bc81.png">

🖕

**Comment by mimikun** [comment]
https://github.com/kadoshita/mastodon/commit/b5ed409b4e6cbdc7db41d294e6db5abcfaf99475
チェリーピックして解決する・・・かもしれんのでやる 感謝感激 🙏

**Comment by mimikun** [comment]
https://github.com/mastodon/mastodon/issues/24177

本家にissueした

**Comment by mimikun** [comment]
issueの・・・異臭！

**Comment by mimikun** [comment]
CSPの存在意義がようわからんので消す。セキュリティは利便性を下げるゴミ要素・・・

https://github.com/mimikun/mastodon/commit/cc572f6f832725305c99ee133ef219cd9f5ba6bf

**Comment by mimikun** [comment]
nginxのconfからも消してみたが、状況変わらず。スマホアプリからなら画像も見れるのでそっちで閲覧を継続する

**Comment by mimikun** [comment]
https://github.com/mimikun/mastodon/commit/7daae051ce9613ce3249dd89dbb0f3da790880fc のコミットで

```ruby
media_host   = host_to_url(ENV['S3_ENDPOINT'])
media_host ||= host_to_url(ENV['S3_BUCKET'])
```

と修正した。俺の環境では `S3_ALIAS_HOST` を設定していないため。

**Comment by mimikun** [comment]
バケットへのアクセス方法 - Amazon Simple Storage Service
https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/access-bucket-intro.html

パス形式のアクセスでやっていたので問題が発生する？

その場合あたらしいURLは `https://mstdn.mimikun.jp.s3.ap-northeast-1.amazonaws.com/key-name` となるのだが

アクセスすると証明書エラーが出る。これは仕様か？

<img width="162" alt="image" src="https://user-images.githubusercontent.com/13450321/226579182-cfcac70d-5e70-4183-87d5-aa3de7be1735.png">

ClourFrontとか使っているわけではない。

**Comment by mimikun** [comment]
https://github.com/mastodon/mastodon/issues/24158
メモ

**Comment by mimikun** [comment]
直った

**Comment by mimikun** [comment]
直ったと思ってたけど再発。
2023年4月2日の10時ごろ。

**Comment by tokpig** [comment]
我也遇到了这样的问题，我无法解决

**Comment by mimikun** [comment]
@tokpig 
我不知道如何修复它，因为我不知道它是何时为我修复的。
在Mastodon上创建一个新问题可能会有帮助。
